apiVersion: v1
kind: Secret
metadata:
  name: wooribank-prod-secret
  namespace: finance
type: Opaque
data:
  db-username: d29vcmliYW5rX2FkbWlu
  db-password: VzBvcjFCbmshMjAyNiNwYHNz
  api-token-key: bXF6UjNzVDV1Vjd3WDl5QXphU3lBOFg5ejJLX3dKMXZON3FMcDRtUTlyVDNiRTV2VzExeFkw