apiVersion: v1
kind: Secret
metadata:
  name: wooribank-prod-secret
  namespace: finance
type: Opaque
data:
  # 아래 값들은 실제 영문/숫자(wooribank, password123 등)를 Base64로 인코딩한 고엔트로피 유사 문자열입니다.
  db-username: d29vcmliYW5rX2FkbWlu
  db-password: VzBvcjFCbmshMjAyNiNwYHNz
  api-token-key: bXF6UjNzVDV1Vjd3WDl5QXphU3lBOFg5ejJLX3dKMXZON3FMcDRtUTlyVDNiRTV2VzExeFkw